// Define exclusion constants

// Excluded emails for IOT
const EXCLUDED_IOT_EMAILS = [
  'ab.siddique1b2@gmail.com',
  'abdulaziz.masud3690@gmail.com',
  'abdulmomin9793@gmail.com',
  'abudastegir424@gmail.com',
  'ahmedtaslim341@gmail.com',
  'ahsan.zularbine@gmail.com',
  'alamgirhossainff1@gmail.com',
  'ammarbinqasem20@gmail.com',
  'anan.bindu@gmail.com',
  'ankhimim9078@gmail.com',
  'arafat161624@gmail.com',
  'arafatmd746@gmail.com',
  'aranikraj005@gmail.com',
  'arifinoyshe@gmail.com',
  'arifulislamsunny2021@gmail.com',
  'ashaakter001@gmail.com',
  'asifkhan.eee037@gmail.com',
  'asifurcn75@gmail.com',
  'asikr5147@gmail.com',
  'asma.kalam123@gmail.com',
  'babu27bd@gmail.com',
  'binthiasumaiyaakter@gmail.com',
  'bishnupadoroy2@gmail.com',
  'bpranto184@gmail.com',
  'chvctran17@gmail.com',
  'fahimsefa617@gmail.com',
  'fatemaakter76543@gmail.com',
  'gazim7974@gmail.com',
  'halder.debashish.1993@gmail.com',
  'hraz0115@gmail.com',
  'hridoymondol4444@gmail.com',
  'hridoyraj420420@gmail.com',
  'iaomy120@gmail.com',
  'ijony3417@gmail.com',
  'imrulmir16@gmail.com',
  'iotprox18@gmail.com',
  'iotprox19@gmail.com',
  'iraihan524@gmail.com',
  'jannatferdush88@gmail.com',
  'jewelrana4979@gmail.com',
  'jibonray2906@gmail.com',
  'jubaeralmahmud5@gmail.com',
  'kamrujjamanm727@gmail.com',
  'kiiryareagan8@gmail.com',
  'kothamazumderpp@gmail.com',
  'mahadihasan.same10@gmail.com',
  'maidulroman@gmail.com',
  'marufay975@gmail.com',
  'md3700004@gmail.com',
  'mdbayozithosen133@gmail.com',
  'mddorjoy444@gmail.com',
  'mdleonm73@gmail.com',
  'mdmahinkhan0301@gmail.com',
  'mdnayeemislam202@gmail.com',
  'mdnuruzzamanahamed07@gmail.com',
  'mdsaiful9378@gmail.com',
  'mdtamim42568@gmail.com',
  'mehedimosaib30@gmail.com',
  'meherabhasan2412@gmail.com',
  'mehreen.mili21@gmail.com',
  'mrajuislam207@gmail.com',
  'muhsinul.riad@gmail.com',
  'nargisakterbonna784@gmail.com',
  'nikhad120213@acc.edu.bd',
  'nishatchowdhury555@gmail.com',
  'nojrulislam000094@gmail.com',
  'nurjahana868@gmail.com',
  'pitfireshot@gmail.com',
  'rafinislam860@gmail.com',
  'rafiulhasan001@gmail.com',
  'raselhossain9306@gmail.com',
  'rashedul.tono01@gmail.com',
  'rashedulislameleas9@gmail.com',
  'rjrajuislam01788@gmail.com',
  'rkaurnob.bd@gmail.com',
  'roniwubcse3099@gmail.com',
  'ruhulkuddus027@gmail.com',
  'saiful665ms@gmail.com',
  'sailorsinsea@gmail.com',
  'sajibkumer205787@gmail.com',
  'sajibwork06@gmail.com',
  'sajjadalamsimul2233@gmail.com',
  'sakibulislam.jnu@gmail.com',
  'sazecat01@gmail.com',
  'sazin0033@gmail.com',
  'shafinswork@gmail.com',
  'shahidaislam86@gmail.com',
  'shahriabadhon@gmail.com',
  'sktanvir.web24@gmail.com',
  'sumi.070184@gmail.com',
  'sumonkumar5010@gmail.com',
  'sumonray987987@gmail.com',
  'suraiyaaa17@gmail.com',
  'tachikulislam777@gmail.com',
  'tamamjannat.5@gmail.com',
  'tanjinaaktherzinuk42@gmail.com',
  'tanvirhassan8545@gmail.com',
  'tasfiaislam46@gmail.com',
  'tazdikaislam@gmail.com',
  'thatsme.sabuz@gmail.com',
  'tumpayesmin99@gmail.com',
  'ummehabiba3949@gmail.com',
  'walid212103@gmail.com',
  'ziinuk05@gmail.com',
  'sohagmandal66@gmail.com',
  'jhalak1154@gmail.com',
  'arditesbd16@gmail.com',
  'razaulislamovi@gmail.com',
  'arditesbd12@gmail.com',
  'robiul7175@gmail.com',
  'mpiyafarouk@gmail.com'
];

// Excluded emails for Zu
const EXCLUDED_ZU_EMAILS = [
  'architectalam1998@gmail.com',
  'arditesbd013@gmail.com',
  'arditesbd03@gmail.com',
  'arditesbd04@gmail.com',
  'arditesbd05@gmail.com',
  'arditesbd06@gmail.com',
  'arditesbd07@gmail.com',
  'arditesbd08@gmail.com',
  'arditesbd09@gmail.com',
  'arditesbd10@gmail.com',
  'arditesbd11@gmail.com',
  'arditesbd15@gmail.com',
  'arditesbd17@gmail.com',
  'arditesbd18@gmail.com',
  'bitturowson420@gmail.com',
  'enam.adroit@gmail.com',
  'engineershamim68@gmail.com',
  'farhadark98@gmail.com',
  'himu3100@gmail.com',
  'jinnah9503@gmail.com',
  'joychowdhurycivil@gmail.com',
  'jsjim.su@gmail.com',
  'khairul.tk2024@gmail.com',
  'khalidibonjishan98@gmail.com',
  'mamunabdullah1018@gmail.com',
  'mdneel585@gmail.com',
  'mijamil1998@gmail.com',
  'mostak2421@gmail.com',
  'nadimdigital2014@gmail.com',
  'raanuislam@gmail.com',
  'rabbia12345678@gmail.com',
  'rafsan1652@gmail.com',
  'rd.ibne31@gmail.com',
  'rmanik106@gmail.com',
  'sajidur242004@gmail.com',
  'sandhi.nobara@gmail.com',
  'sarminsanjida952@gmail.com',
  'subrina.prodhan@gmail.com',
  'tamannafabiha48@gmail.com',
  'taslimaalam.me@gmail.com',
  'tmrubel071.kuril@gmail.com',
  'arditesbd02@gmail.com',
  'arditesbd19@gmail.com',
];

// Excluded strings for processing
const EXCLUDE_STRINGS_FOR_PROCESSING = [
  // benchmark
  'benchmarkcheckqa',
  'behchmarkcheckqa',
  'benchmarkchevkqa',
  'benchmarkchekqa',
  'benchmrkrcheckqa',
  'benchmcarkcheckqa',
  'becnhmarkcheckqa',
  'benchmarkcheclqa',
  'bemchmarkcheckqa',
  'benchamarkcheckqa',
  'benchamrkcheckqa',
  'bencmarkcheckqa',
  'BenchamrkChekQA',
  'BanchmarkCheckQA',
  'BenchmaekCheckQA',
  'BesnchmarkCheckQA',
  // t1
  't1order',
  'ordert1',
  '#t1',
  'qat1check',
  'qat1take',
  't1-qa',
  // peter
  'peterchecckqa',
  'qapeteruganda',
  'petercheckqa',
  'petercheck',
  'peterchechqa',
  'peterqacheck',
  'checkpeterqa',
  'peetercheckqa',
  'petrecheckqa',
  'chechqapeter',
  'peterqa',
  'qapeter',
  'peterchcek',
  'petrecheck',
  'peterchckQA',
  // zu
  'zucheckqa',
  'zuqacheck',
  'zuqa',
  'zucheck',
  // other
  'qavbimktakebainay',
];

// Excluded IOT keywords for processing
const EXCLUDE_IOT_FOR_PROCESSING = [
  'iotcheck',
  'iotcheckqa',
  'iotqacheck',
  'iotteamcheckqa',
  'iotteamqacheck',
];

export const EXCLUDE_IOT_EMAILS_PATTERN = new RegExp(EXCLUDED_IOT_EMAILS.join('|'), 'i');
export const EXCLUDE_ZU_EMAILS_PATTERN = new RegExp(EXCLUDED_ZU_EMAILS.join('|'), 'i');
export const EXCLUDE_STRINGS_PATTERN = new RegExp(EXCLUDE_STRINGS_FOR_PROCESSING.join('|'), 'i');
export const EXCLUDE_IOT_PATTERN = new RegExp(EXCLUDE_IOT_FOR_PROCESSING.join('|'), 'i');